a3q2: set.h set.o main.c
	clang -Wall main.c set.o -o a3q2

set1: set.h set1.o main.c
	clang -Wall main.c set1.o -o set1

set2: set.h set2.o main.c
	clang -Wall main.c set2.o -o set2

set3: set.h set3.o main.c
	clang -Wall main.c set3.o -o set3

set4: set.h set4.o main.c
	clang -Wall main.c set4.o -o set4

set5: set.h set5.o main.c
	clang -Wall main.c set5.o -o set5

clean: 
	rm a3q2 set1 set2 set3 set4 set5
 
